export const herdmentalityquestions = [
  {
    category: "Food",
    question: "What’s the best topping for pizza?",
    options: [
      "Pepperoni",
      "Cheese",
      "Mushrooms",
      "Pineapple",
      "Olives",
      "Onions",
    ],
  },
  {
    category: "Food",
    question: "What’s the best dessert?",
    options: ["Ice cream", "Cake", "Cookies", "Brownies", "Pie", "Donuts"],
  },
  {
    category: "Food",
    question: "What’s the best drink to have with breakfast?",
    options: [
      "Orange juice",
      "Coffee",
      "Milk",
      "Tea",
      "Hot chocolate",
      "Water",
    ],
  },
  {
    category: "Food",
    question: "What’s the best sandwich filling?",
    options: [
      "Ham and cheese",
      "Peanut butter and jelly",
      "Turkey",
      "Tuna",
      "Egg salad",
      "Grilled cheese",
    ],
  },
  {
    category: "Food",
    question: "What’s the best fruit?",
    options: ["Apple", "Banana", "Strawberry", "Mango", "Grapes", "Watermelon"],
  },
  {
    category: "Food",
    question: "What’s the best kind of soup?",
    options: [
      "Tomato",
      "Chicken noodle",
      "Mushroom",
      "Minestrone",
      "Pumpkin",
      "Vegetable",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best season of the year?",
    options: [
      "Summer",
      "Winter",
      "Spring",
      "Autumn",
      "All of them",
      "None of them",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best way to relax?",
    options: [
      "Watching TV",
      "Reading",
      "Listening to music",
      "Taking a nap",
      "Going for a walk",
      "Playing games",
    ],
  },
  {
    category: "Lifestyle",
    question: "Which holiday is the most fun?",
    options: [
      "Christmas",
      "Halloween",
      "Easter",
      "Thanksgiving",
      "New Year’s Eve",
      "Valentine’s Day",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best time of day?",
    options: ["Morning", "Afternoon", "Evening", "Night", "Midday", "Sunset"],
  },
  {
    category: "Lifestyle",
    question: "What’s the best outdoor activity?",
    options: [
      "Picnic",
      "Hiking",
      "Cycling",
      "Swimming",
      "Playing sports",
      "Gardening",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best board game?",
    options: [
      "Monopoly",
      "Scrabble",
      "Clue",
      "Uno",
      "Chess",
      "The Game of Life",
    ],
  },
  {
    category: "Pop Culture",
    question: "Who’s the best Disney character?",
    options: [
      "Mickey Mouse",
      "Donald Duck",
      "Elsa",
      "Simba",
      "Buzz Lightyear",
      "Goofy",
    ],
  },
  {
    category: "Pop Culture",
    question: "What’s the best animated movie?",
    options: [
      "Toy Story",
      "Frozen",
      "The Lion King",
      "Shrek",
      "Finding Nemo",
      "Inside Out",
    ],
  },
  {
    category: "Pop Culture",
    question: "What’s the best superhero?",
    options: [
      "Spider-Man",
      "Batman",
      "Superman",
      "Iron Man",
      "Wonder Woman",
      "Captain America",
    ],
  },
  {
    category: "Pop Culture",
    question: "What’s the best TV show for families?",
    options: [
      "Bluey",
      "The Simpsons",
      "SpongeBob SquarePants",
      "Friends",
      "Full House",
      "Modern Family",
    ],
  },
  {
    category: "Pop Culture",
    question: "Which game console is the best?",
    options: ["Nintendo Switch", "PlayStation", "Xbox", "PC", "Mobile", "None"],
  },
  {
    category: "Pop Culture",
    question: "What’s the best song to dance to?",
    options: [
      "Happy",
      "Uptown Funk",
      "Shake It Off",
      "Can’t Stop the Feeling",
      "Dance Monkey",
      "Let It Go",
    ],
  },
  {
    category: "Animals",
    question: "What’s the best animal?",
    options: ["Dog", "Cat", "Horse", "Elephant", "Dolphin", "Lion"],
  },
  {
    category: "Animals",
    question: "What’s the cutest animal?",
    options: ["Puppy", "Kitten", "Panda", "Bunny", "Koala", "Penguin"],
  },
  {
    category: "Animals",
    question: "Which animal would make the best pet (if possible)?",
    options: ["Tiger", "Monkey", "Dolphin", "Panda", "Elephant", "Parrot"],
  },
  {
    category: "Animals",
    question: "Which animal would you be?",
    options: ["Lion", "Cat", "Dog", "Eagle", "Dolphin", "Sloth"],
  },
  {
    category: "Animals",
    question: "What’s the best farm animal?",
    options: ["Cow", "Pig", "Chicken", "Horse", "Sheep", "Goat"],
  },
  {
    category: "Animals",
    question: "What’s the scariest animal?",
    options: ["Snake", "Spider", "Shark", "Lion", "Crocodile", "Bear"],
  },
  {
    category: "Hypotheticals",
    question: "If you could live anywhere, where would it be?",
    options: ["Beach", "Mountains", "City", "Countryside", "Forest", "Island"],
  },
  {
    category: "Hypotheticals",
    question: "If you could only eat one food forever, what would it be?",
    options: ["Pizza", "Pasta", "Burgers", "Ice cream", "Chicken", "Salad"],
  },
  {
    category: "Hypotheticals",
    question: "If you could have any job, what would it be?",
    options: ["Doctor", "Teacher", "Athlete", "Actor", "Scientist", "Artist"],
  },
  {
    category: "Hypotheticals",
    question: "If you could travel in time, where would you go?",
    options: [
      "Past",
      "Future",
      "Prehistoric era",
      "Medieval times",
      "1960s",
      "Never travel",
    ],
  },
  {
    category: "Hypotheticals",
    question: "If you could talk to one animal, which would it be?",
    options: ["Dog", "Cat", "Dolphin", "Bird", "Elephant", "Horse"],
  },
  {
    category: "Hypotheticals",
    question: "If you found a magic lamp, what would you wish for?",
    options: [
      "Money",
      "Happiness",
      "World peace",
      "Fame",
      "Health",
      "More wishes",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best thing to do on the weekend?",
    options: [
      "Sleep in",
      "Go out",
      "Watch movies",
      "Play games",
      "Hang out with friends",
      "Relax at home",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the worst household chore?",
    options: [
      "Doing dishes",
      "Laundry",
      "Vacuuming",
      "Cleaning the bathroom",
      "Dusting",
      "Taking out the trash",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best subject in school?",
    options: [
      "Math",
      "Science",
      "English",
      "Art",
      "History",
      "Physical Education",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best ice cream flavor?",
    options: [
      "Vanilla",
      "Chocolate",
      "Strawberry",
      "Mint chocolate chip",
      "Cookie dough",
      "Caramel",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best toy of all time?",
    options: [
      "LEGO",
      "Barbie",
      "Hot Wheels",
      "Teddy bear",
      "Rubik’s Cube",
      "Action figures",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best way to start the day?",
    options: [
      "Breakfast",
      "Exercise",
      "Shower",
      "Music",
      "Coffee",
      "Sleeping in",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best form of transport?",
    options: ["Car", "Bike", "Bus", "Train", "Plane", "Walking"],
  },
  {
    category: "Everyday Life",
    question: "What’s the best thing about weekends?",
    options: [
      "Sleeping late",
      "No school/work",
      "Family time",
      "Going out",
      "Relaxing",
      "Watching TV",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best meal of the day?",
    options: [
      "Breakfast",
      "Lunch",
      "Dinner",
      "Snack time",
      "Dessert",
      "Brunch",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best thing to watch on TV?",
    options: [
      "Cartoons",
      "Movies",
      "Sports",
      "News",
      "Reality shows",
      "Documentaries",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best thing to do on a rainy day?",
    options: [
      "Watch movies",
      "Read",
      "Sleep",
      "Bake",
      "Play games",
      "Listen to music",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best part of summer?",
    options: [
      "Swimming",
      "Ice cream",
      "No school",
      "Traveling",
      "Sunshine",
      "Outdoor fun",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best thing to do on your birthday?",
    options: [
      "Have a party",
      "Eat cake",
      "Open gifts",
      "Go out",
      "Stay home",
      "Invite friends",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best indoor activity?",
    options: [
      "Watching TV",
      "Reading",
      "Playing games",
      "Cooking",
      "Drawing",
      "Building with LEGO",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best holiday activity?",
    options: [
      "Traveling",
      "Eating",
      "Sleeping",
      "Visiting family",
      "Shopping",
      "Playing games",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best ice cream topping?",
    options: [
      "Sprinkles",
      "Chocolate syrup",
      "Caramel",
      "Nuts",
      "Whipped cream",
      "Cherries",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best kind of weather?",
    options: ["Sunny", "Rainy", "Snowy", "Windy", "Cloudy", "Cool and breezy"],
  },
  {
    category: "Everyday Life",
    question: "What’s the best thing about school?",
    options: ["Friends", "Recess", "Lunch", "Learning", "Teachers", "Holidays"],
  },
  {
    category: "Everyday Life",
    question: "What’s the best thing to have for breakfast?",
    options: ["Pancakes", "Cereal", "Eggs", "Toast", "Waffles", "Smoothie"],
  },
  {
    category: "Food",
    question: "What’s the best side with fast food?",
    options: [
      "Fries",
      "Onion rings",
      "Coleslaw",
      "Mozzarella sticks",
      "Nuggets",
      "Salad",
    ],
  },
  {
    category: "Food",
    question: "What’s the best breakfast food?",
    options: [
      "Pancakes",
      "Eggs",
      "Bacon",
      "Waffles",
      "French toast",
      "Oatmeal",
    ],
  },
  {
    category: "Food",
    question: "What’s the best comfort food?",
    options: [
      "Mac and cheese",
      "Pizza",
      "Mashed potatoes",
      "Fried chicken",
      "Soup",
      "Ramen",
    ],
  },
  {
    category: "Food",
    question: "What’s the best street food?",
    options: ["Tacos", "Hot dogs", "Kebabs", "Crepes", "Dumplings", "Pretzels"],
  },
  {
    category: "Food",
    question: "What’s the best potato chip flavor?",
    options: [
      "Salted",
      "Barbecue",
      "Sour cream and onion",
      "Cheese",
      "Vinegar",
      "Spicy chili",
    ],
  },
  {
    category: "Food",
    question: "What’s the best party snack?",
    options: [
      "Popcorn",
      "Nachos",
      "Chips and dip",
      "Chicken wings",
      "Mini sandwiches",
      "Fruit platter",
    ],
  },
  {
    category: "Food",
    question: "What’s the best pasta shape?",
    options: [
      "Spaghetti",
      "Penne",
      "Fusilli",
      "Macaroni",
      "Farfalle",
      "Lasagna sheets",
    ],
  },
  {
    category: "Food",
    question: "What’s the best way to eat eggs?",
    options: [
      "Scrambled",
      "Fried",
      "Boiled",
      "Poached",
      "Omelette",
      "Sunny-side up",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best hobby to pick up?",
    options: [
      "Reading",
      "Gaming",
      "Cooking",
      "Drawing",
      "Gardening",
      "Photography",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best weekend plan?",
    options: [
      "Stay home",
      "Go out with friends",
      "Travel",
      "Watch movies",
      "Play sports",
      "Sleep",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best way to stay active?",
    options: [
      "Walking",
      "Gym workouts",
      "Dancing",
      "Cycling",
      "Team sports",
      "Yoga",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best app to use daily?",
    options: [
      "YouTube",
      "WhatsApp",
      "Instagram",
      "Spotify",
      "Google Maps",
      "TikTok",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best music for focus?",
    options: [
      "Lo-fi",
      "Classical",
      "Instrumental",
      "Jazz",
      "Ambient",
      "Silence",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best kind of vacation?",
    options: [
      "Beach",
      "City trip",
      "Road trip",
      "Mountain retreat",
      "Cruise",
      "Staycation",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best evening routine?",
    options: [
      "Watch a show",
      "Read a book",
      "Take a walk",
      "Call a friend",
      "Play games",
      "Early sleep",
    ],
  },
  {
    category: "Lifestyle",
    question: "What’s the best thing to do before bed?",
    options: [
      "Brush teeth",
      "Read",
      "Pray",
      "Listen to music",
      "Meditate",
      "Set alarm",
    ],
  },
  {
    category: "Pop Culture",
    question: "What’s the best movie franchise?",
    options: [
      "Marvel",
      "Star Wars",
      "Harry Potter",
      "Fast & Furious",
      "The Lord of the Rings",
      "Jurassic Park",
    ],
  },
  {
    category: "Pop Culture",
    question: "What’s the best streaming platform?",
    options: ["Netflix", "Disney+", "Prime Video", "Hulu", "Max", "YouTube"],
  },
  {
    category: "Pop Culture",
    question: "What’s the best sitcom catchphrase?",
    options: [
      "How you doin'?",
      "D'oh!",
      "Bazinga!",
      "Suit up!",
      "No soup for you!",
      "That's what she said",
    ],
  },
  {
    category: "Pop Culture",
    question: "What’s the best animated TV series?",
    options: [
      "The Simpsons",
      "Avatar: The Last Airbender",
      "SpongeBob SquarePants",
      "Rick and Morty",
      "Bluey",
      "Adventure Time",
    ],
  },
  {
    category: "Pop Culture",
    question: "What’s the best movie villain?",
    options: [
      "The Joker",
      "Darth Vader",
      "Thanos",
      "Voldemort",
      "Loki",
      "Scar",
    ],
  },
  {
    category: "Pop Culture",
    question: "What’s the best superhero team?",
    options: [
      "The Avengers",
      "Justice League",
      "X-Men",
      "Guardians of the Galaxy",
      "Teen Titans",
      "Fantastic Four",
    ],
  },
  {
    category: "Pop Culture",
    question: "What’s the best video game character?",
    options: ["Mario", "Link", "Master Chief", "Kratos", "Sonic", "Pikachu"],
  },
  {
    category: "Pop Culture",
    question: "What’s the best kind of concert experience?",
    options: [
      "Pop concert",
      "Rock concert",
      "Festival",
      "Small live gig",
      "Orchestra",
      "DJ set",
    ],
  },
  {
    category: "Animals",
    question: "What’s the smartest animal?",
    options: ["Dolphin", "Chimpanzee", "Elephant", "Crow", "Octopus", "Dog"],
  },
  {
    category: "Animals",
    question: "What’s the best bird?",
    options: ["Eagle", "Parrot", "Owl", "Penguin", "Peacock", "Falcon"],
  },
  {
    category: "Animals",
    question: "What’s the most majestic sea creature?",
    options: ["Whale", "Dolphin", "Sea turtle", "Manta ray", "Shark", "Orca"],
  },
  {
    category: "Animals",
    question: "What’s the best zoo animal to watch?",
    options: ["Giraffe", "Elephant", "Lion", "Panda", "Monkey", "Penguin"],
  },
  {
    category: "Animals",
    question: "What’s the best animal sound?",
    options: [
      "Birdsong",
      "Cat purr",
      "Dog bark",
      "Whale song",
      "Frog croak",
      "Horse neigh",
    ],
  },
  {
    category: "Animals",
    question: "What’s the cutest baby animal name?",
    options: ["Puppy", "Kitten", "Calf", "Cub", "Chick", "Foal"],
  },
  {
    category: "Hypotheticals",
    question: "If you could have one superpower, what would it be?",
    options: [
      "Flying",
      "Invisibility",
      "Teleportation",
      "Mind reading",
      "Super strength",
      "Time control",
    ],
  },
  {
    category: "Hypotheticals",
    question: "If you could own any car, which would you choose?",
    options: [
      "Lamborghini",
      "Tesla",
      "Ferrari",
      "G-Wagon",
      "Porsche",
      "Classic Mustang",
    ],
  },
  {
    category: "Hypotheticals",
    question: "If you could master one skill instantly, what would it be?",
    options: [
      "Singing",
      "Coding",
      "Cooking",
      "Public speaking",
      "Dancing",
      "Playing piano",
    ],
  },
  {
    category: "Hypotheticals",
    question: "If you could live in one fictional world, which would it be?",
    options: [
      "Hogwarts",
      "Wakanda",
      "Middle-earth",
      "Star Wars galaxy",
      "Pokémon world",
      "Narnia",
    ],
  },
  {
    category: "Hypotheticals",
    question:
      "If you were stranded on an island, what’s the one thing you’d bring?",
    options: ["Phone", "Knife", "Water filter", "Tent", "Book", "Friend"],
  },
  {
    category: "Hypotheticals",
    question: "If money was no issue, what would you do this weekend?",
    options: [
      "Travel abroad",
      "Host a big party",
      "Go on a shopping spree",
      "Relax at a resort",
      "Try a new hobby",
      "Help others",
    ],
  },
  {
    category: "Hypotheticals",
    question: "If you could be invisible for one day, what would you do?",
    options: [
      "Explore places",
      "Prank friends",
      "Skip lines",
      "Listen to secrets",
      "Watch a concert backstage",
      "Stay home",
    ],
  },
  {
    category: "Hypotheticals",
    question: "If you could teleport right now, where would you go?",
    options: ["Paris", "Tokyo", "New York", "Dubai", "Bali", "Home"],
  },
  {
    category: "Everyday Life",
    question: "What’s the best app for chatting?",
    options: [
      "WhatsApp",
      "iMessage",
      "Telegram",
      "Messenger",
      "Snapchat",
      "Discord",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best thing to keep in your backpack?",
    options: [
      "Water bottle",
      "Snacks",
      "Notebook",
      "Power bank",
      "Headphones",
      "Umbrella",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best after-school or after-work activity?",
    options: [
      "Gym",
      "Gaming",
      "Reading",
      "Watching shows",
      "Meeting friends",
      "Taking a nap",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best way to save money?",
    options: [
      "Budgeting",
      "Cooking at home",
      "Avoiding impulse buys",
      "Using discounts",
      "Saving automatically",
      "Tracking expenses",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best quick lunch?",
    options: [
      "Sandwich",
      "Instant noodles",
      "Salad",
      "Rice bowl",
      "Wrap",
      "Leftovers",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best snack on a rainy day?",
    options: [
      "Popcorn",
      "Cookies",
      "Tea and biscuits",
      "Instant ramen",
      "Toast",
      "Chips",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best way to organize your room?",
    options: [
      "Declutter first",
      "Use storage boxes",
      "Label shelves",
      "Make the bed",
      "Sort by category",
      "Clean a little daily",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best smell in the world?",
    options: [
      "Fresh bread",
      "Rain",
      "Coffee",
      "Perfume",
      "BBQ",
      "Fresh laundry",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best thing about mornings?",
    options: [
      "Fresh start",
      "Breakfast",
      "Quiet time",
      "Cool weather",
      "Exercise",
      "Sunrise",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best thing about evenings?",
    options: [
      "Relaxing",
      "Dinner",
      "Family time",
      "Watching shows",
      "Gaming",
      "Sleeping soon",
    ],
  },
  {
    category: "Everyday Life",
    question: "What’s the best family game night snack?",
    options: ["Popcorn", "Pizza", "Chips", "Cookies", "Fruit", "Nachos"],
  },
  {
    category: "Everyday Life",
    question: "What’s the best way to celebrate a small win?",
    options: [
      "Treat yourself",
      "Share with friends",
      "Take a break",
      "Post about it",
      "Buy a snack",
      "Reflect and plan next goal",
    ],
  },
];
